import type {Metadata, Viewport} from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "@/app/components/Topbar";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Jidelnicek",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
    title: "Jidelnicek",
    description: "Aplikace pro správu receptů a lednice",
    manifest: "/manifest.json",
    appleWebApp: {
        capable: true,
        statusBarStyle: "default",
        title: "Jidelnicek",
    },
};

export const viewport: Viewport = {
    themeColor: "#4A4870",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="cs"
          className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col bg-background text-foreground">
            <AuthProvider>

                    <Topbar />

                    <main className="grow max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-8">
                        {children}
                    </main>

                    <footer className="border-t py-4 text-center text-sm text-gray-500 bg-white">
                      © {new Date().getFullYear()} Jídelníček
                    </footer>
                </AuthProvider>
            </body>
      </html>
  );
}
